# Generated by Django 5.2.17 on 2026-08-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('REVENUE_INTEREST', 'Interest Income Collected'), ('REVENUE_FEE', 'Loan Application & Processing Fees'), ('REVENUE_PENALTY', 'Late Penalty Revenue'), ('LOSS_BAD_DEBT', 'Bad Debt Write-off / Default Loss'), ('LOSS_NPL_PROVISION', 'Provision for Non-Performing Loans (NPL)')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_logs', to='branches.branch')),
            ],
            options={
                'db_table': 'fkf_ems_financial_logs',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
