# Generated by Django 5.2.17 on 2026-08-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
        ('branches', '0005_branch_allocated_capital_branchcapitalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('INTERNAL', 'Ukaguzi wa Ndani (Internal Audit)'), ('EXTERNAL', 'Ukaguzi wa Nje (External Audit)'), ('SYSTEM', 'System Security & Activity Audit')], default='INTERNAL', max_length=20)),
                ('performed_by', models.CharField(help_text='Mkaguzi / User ID', max_length=150)),
                ('action_title', models.CharField(help_text='Kichwa cha ukaguzi au mabadiliko ya mahesabu', max_length=250)),
                ('details', models.TextField(help_text='Mchanganuo kamili wa ukaguzi')),
                ('severity', models.CharField(choices=[('INFO', 'Taarifa ya Kawaida'), ('WARNING', 'Onyo la Mahesabu'), ('CRITICAL', 'Kasoro Kubwa / Discrepancy')], default='INFO', max_length=15)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='branches.branch')),
            ],
            options={
                'db_table': 'fkf_ems_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
