# Generated by Django 5.2.17 on 2026-08-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRBCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CREDITINFO', 'Creditinfo Kenya CRB'), ('METROPOL', 'Metropol CRB Kenya')], default='CREDITINFO', max_length=30)),
                ('credit_score', models.IntegerField(help_text='Credit score ranging from 200 to 900')),
                ('status', models.CharField(choices=[('CLEARED', 'Cleared / Low Risk (200 Certificate)'), ('PERFORMING', 'Performing Active Accounts'), ('NON_PERFORMING', 'Non-Performing Accounts Flagged'), ('BLACKLISTED', 'Blacklisted / Severe Defaulter')], default='PERFORMING', max_length=30)),
                ('delinquent_accounts_count', models.IntegerField(default=0)),
                ('total_delinquent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('summary', models.TextField(blank=True, null=True)),
                ('request_payload', models.TextField(blank=True, help_text='Sent JSON API Payload', null=True)),
                ('response_payload', models.TextField(blank=True, help_text='Received JSON API Response', null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crb_checks', to='loans.borrower')),
            ],
            options={
                'db_table': 'fkf_ems_crb_checks',
                'ordering': ['-checked_at'],
            },
        ),
    ]
