# Generated by Django 5.2.17 on 2026-08-06 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('VEHICLE', 'Motor Vehicle / Fleet'), ('LAND_TITLE', 'Land Title Deed / Plot'), ('COMMERCIAL_PROPERTY', 'Commercial Real Estate'), ('EQUIPMENT', 'Heavy Equipment / Machinery'), ('STOCKS_ASSETS', 'Inventory / Shares & Financial Assets')], default='VEHICLE', max_length=30)),
                ('title_deed_or_reg_number', models.CharField(help_text='Registration No. / Title Deed No. / Logbook No.', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of physical condition, location, specs')),
                ('estimated_market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forced_sale_value', models.DecimalField(decimal_places=2, help_text='Liquidation / Forced Sale Value', max_digits=12)),
                ('calculated_ltv_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Loan-to-Value Ratio (%)', max_digits=5)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=60, null=True)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('valuation_expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Inspection'), ('VERIFIED', 'Verified & Charge Registered'), ('EXPIRED', 'Document / Insurance Expired'), ('FLAGGED', 'High Risk / Dispute Flagged')], default='PENDING', max_length=20)),
                ('document_url', models.CharField(blank=True, help_text='Path or URL to uploaded ownership title deed / logbook PDF', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.borrower')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='loans.loan')),
            ],
            options={
                'db_table': 'fkf_ems_collaterals',
                'ordering': ['-created_at'],
            },
        ),
    ]
