# Generated by Django 5.2.17 on 2026-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
