# Generated by Django 5.2.17 on 2026-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_passport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrower_id',
            field=models.IntegerField(blank=True, help_text='Linked Borrower Model Record ID', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'IT / Super Admin'), ('BRANCH_MANAGER', 'Branch Manager'), ('LOAN_OFFICER', 'Loan Officer'), ('RISK_OFFICER', 'Risk Officer'), ('BORROWER', 'Mteja / Mkopaji')], default='LOAN_OFFICER', max_length=25),
        ),
    ]
