# Generated by Django 5.2.17 on 2026-08-11 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_borrower_id_alter_user_role'),
        ('branches', '0005_branch_allocated_capital_branchcapitalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Mshahara wa Msingi TSH', max_digits=14),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_nhif',
            field=models.BooleanField(default=True, help_text='Kukata Bima ya Afya 3%?'),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_nssf',
            field=models.BooleanField(default=True, help_text='Kukata NSSF 10%?'),
        ),
        migrations.AddField(
            model_name='user',
            name='field_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Posho ya Field / Kazi TSH', max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Posho ya Nyumba / Chakula TSH', max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='nhif_number',
            field=models.CharField(blank=True, help_text='Namba ya Bima ya Afya NHIF', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nssf_number',
            field=models.CharField(blank=True, help_text='Namba ya NSSF ya Mtumishi', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_account_no',
            field=models.CharField(blank=True, help_text='Namba ya Akaunti au Simu ya Kupokelea Mshahara', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(default='MOBILE_MONEY', help_text='MOBILE_MONEY | BANK_ACCOUNT', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_provider',
            field=models.CharField(default='M-Pesa', help_text='M-Pesa, NMB, CRDB, Tigo Pesa, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Posho ya Usafiri TSH', max_digits=12),
        ),
        migrations.CreateModel(
            name='FieldExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FIELD_TRANSPORT', 'Usafiri wa Field / Nauli'), ('FUEL', 'Mafuta ya Pikipiki / Gari'), ('LODGING', 'Lodging / Malazi'), ('MEALS', 'Chakula Nje ya Ofisi'), ('OFFICE_STATIONERY', 'Vifaa vya Ofisi / Printing'), ('CLIENT_MEETING', 'Mkutano wa Wateja / Kikundi'), ('OTHER', 'Matumizi Mengineyo')], default='FIELD_TRANSPORT', max_length=40)),
                ('title', models.CharField(help_text='Maelezo ya matumizi ya kazi', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kiasi TSH', max_digits=12)),
                ('receipt_no', models.CharField(blank=True, help_text='Namba ya Risiti / Kumbukumbu', max_length=100, null=True)),
                ('receipt_attachment', models.TextField(blank=True, help_text='Base64 Image of Receipt', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Inasubiri Idhini'), ('APPROVED', 'Imeidhinishwa & Kulipwa'), ('REJECTED', 'Imekataliwa')], default='PENDING', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_expenses', to='branches.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fkf_ems_field_expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
