# Generated by Django 5.2.17 on 2026-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_jobvacancy_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='flyer_attachment',
            field=models.TextField(blank=True, help_text='Base64/URL JPG/PNG/PDF Job Advert Poster Flyer', null=True),
        ),
    ]
