# Generated by Django 5.2.17 on 2026-08-11 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_jobvacancy_flyer_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'IT / Super Admin'), ('BRANCH_MANAGER', 'Branch Manager'), ('LOAN_OFFICER', 'Loan Officer'), ('RISK_OFFICER', 'Risk Officer'), ('BORROWER', 'Mteja / Mkopaji'), ('JOB_APPLICANT', 'Mwombaji Kazi (Job Applicant)')], default='LOAN_OFFICER', max_length=25),
        ),
    ]
