# Generated by Django 5.2.17 on 2026-08-06 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(help_text='National ID / Passport Number', max_length=30, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(max_length=200)),
                ('employment_status', models.CharField(choices=[('SALARIED', 'Salaried Employee'), ('SELF_EMPLOYED', 'Self-Employed / Business'), ('CIVIL_SERVANT', 'Civil Servant'), ('CONTRACTOR', 'Contractor / Freelance')], default='SALARIED', max_length=25)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=50000.0, max_digits=12)),
                ('credit_rating', models.CharField(default='GOOD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='branches.branch')),
            ],
            options={
                'db_table': 'fkf_ems_borrowers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=40, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, help_text='Applied interest rate per term', max_digits=5)),
                ('term_months', models.IntegerField(default=12)),
                ('repayment_frequency', models.CharField(default='MONTHLY', max_length=20)),
                ('penalty_type', models.CharField(default='PERCENTAGE', max_length=15)),
                ('penalty_value', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_RISK_REVIEW', 'Pending Risk Review'), ('PENDING_BRANCH_APPROVAL', 'Pending Branch Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed & Active'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted / Non-Performing'), ('CLOSED', 'Fully Settled / Closed')], default='PENDING_RISK_REVIEW', max_length=30)),
                ('risk_score', models.IntegerField(default=75)),
                ('risk_grade', models.CharField(choices=[('LOW', 'Low Risk (Score 80-100)'), ('MEDIUM', 'Medium Risk (Score 60-79)'), ('HIGH', 'High Risk (Score 40-59)'), ('CRITICAL', 'Critical Risk (Score < 40)')], default='LOW', max_length=20)),
                ('disbursed_at', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance_remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.borrower')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='branches.branch')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fkf_ems_loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa Mobile Money'), ('BANK_TRANSFER', 'Bank Wire / RTGS'), ('CASH', 'Cash Branch Counter'), ('CHEQUE', 'Banker Cheque')], default='MPESA', max_length=25)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fkf_ems_repayments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
