# Generated by Django 5.2.17 on 2026-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='photo_url',
            field=models.TextField(blank=True, help_text='Passport Size Photo URL or Base64 Image', null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id_number',
            field=models.CharField(help_text='Tanzania NIDA National ID / Passport Number', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA_TZ', 'M-Pesa Tanzania'), ('TIGO_PESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money Tanzania'), ('BANK_TRANSFER', 'CRDB / NMB Bank Transfer'), ('CASH', 'Cash Branch Counter'), ('CHEQUE', 'Banker Cheque')], default='MPESA_TZ', max_length=25),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='penalty_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
