# Generated by Django 5.2.17 on 2026-08-06 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_borrower_photo_url_alter_borrower_id_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='penalty_type',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='penalty_value',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='repayment_frequency',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='risk_grade',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='recorded_by',
        ),
        migrations.AddField(
            model_name='borrower',
            name='kyc_notes',
            field=models.TextField(blank=True, default='NIDA Registration Verified', null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='kyc_status',
            field=models.CharField(choices=[('PENDING', 'Kyc Pending Review'), ('VERIFIED', 'Verified & Approved (NIDA Passed)'), ('REJECTED', 'Rejected / Suspicious ID')], default='VERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='borrower',
            name='verified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originated_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate_pct',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_RISK_REVIEW', 'Pending Risk Review'), ('PENDING_BRANCH_APPROVAL', 'Pending Branch Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed & Active'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted / Non-Performing'), ('CLOSED', 'Closed / Fully Repaid')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'Vodacom M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTELMONEY', 'Airtel Money'), ('BANK', 'CRDB / NMB Bank Transfer'), ('CASH', 'Branch Counter Cash')], default='MPESA', max_length=20),
        ),
    ]
