# Generated by Django 5.2.17 on 2026-08-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_due_date_remove_loan_loan_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_officer',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='monthly_installment',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_interest',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='interest_paid',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='penalty_paid',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='principal_paid',
        ),
        migrations.AddField(
            model_name='borrower',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='gender',
            field=models.CharField(blank=True, default='- Select -', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='house_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='id_type',
            field=models.CharField(default='NIDA', max_length=50),
        ),
        migrations.AddField(
            model_name='borrower',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='plot_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='borrower',
            name='street_or_village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_RISK_REVIEW', 'Pending Risk Review'), ('PENDING_BRANCH_APPROVAL', 'Pending Branch Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed & Active'), ('REJECTED', 'Rejected'), ('DEFAULTED', 'Defaulted / Non-Performing'), ('CLOSED', 'Closed / Fully Repaid')], default='PENDING_RISK_REVIEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA_TZ', 'Vodacom M-Pesa (Tanzania)'), ('TIGO_PESA', 'Tigo Pesa (Tanzania)'), ('AIRTEL_MONEY', 'Airtel Money (Tanzania)'), ('HALOPESA', 'HaloPesa (Tanzania)'), ('BANK_NMB', 'NMB Bank Account Transfer'), ('BANK_CRDB', 'CRDB Bank Account Transfer'), ('CASH_BRANCH', 'Cash Counter Payment at Branch')], default='MPESA_TZ', max_length=30),
        ),
    ]
