# Generated by Django 5.2.17 on 2026-08-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_region_district_ward_street'),
        ('loans', '0004_remove_loan_loan_officer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='term_months',
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=145000.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure_months',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='balance_remaining',
            field=models.DecimalField(decimal_places=2, default=1145000.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate_pct',
            field=models.DecimalField(decimal_places=2, default=14.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING_BRANCH_APPROVAL', 'Pending Branch Manager Approval'), ('PENDING_RISK_REVIEW', 'Pending Risk Officer Audit'), ('APPROVED', 'Approved by Branch Management'), ('DISBURSED', 'Disbursed to Borrower'), ('REPAID', 'Fully Repaid'), ('DEFAULTED', 'Defaulted / Under Recovery')], default='PENDING_BRANCH_APPROVAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=1145000.0, max_digits=14),
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('max_amount', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=14)),
                ('min_duration', models.IntegerField(default=1)),
                ('max_duration', models.IntegerField(default=12)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, default=14.5, max_digits=5)),
                ('interest_type', models.CharField(default='Flat', max_length=50)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=14)),
                ('penalty_type', models.CharField(default='Percentage', max_length=50)),
                ('repayment_frequency', models.CharField(default='Monthly', max_length=50)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('vat_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grace_days', models.IntegerField(default=0)),
                ('guarantor_required', models.CharField(default='Yes', max_length=20)),
                ('no_of_guarantors', models.IntegerField(default=1)),
                ('collateral_required', models.CharField(default='No', max_length=20)),
                ('req_nida', models.CharField(default='Required', max_length=30)),
                ('req_tin', models.CharField(default='Not Required', max_length=30)),
                ('req_kadi_ya_chama', models.CharField(default='Not Required', max_length=30)),
                ('req_leseni_ya_biashara', models.CharField(default='Not Required', max_length=30)),
                ('req_picha_ya_biashara', models.CharField(default='Not Required', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='branches.branch')),
            ],
            options={
                'db_table': 'fkf_ems_loan_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.loanproduct'),
        ),
    ]
