# Generated by Django 5.2.17 on 2026-08-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loan_term_months_loan_interest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('DAILY', 'Kila Siku / Daily'), ('WEEKLY', 'Kila Wiki / Weekly'), ('MONTHLY', 'Kila Mwezi / Monthly')], default='MONTHLY', max_length=30),
        ),
    ]
