# Generated by Django 5.2.17 on 2026-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_repayment_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursed_branch_name',
            field=models.CharField(blank=True, help_text='Tawi ambapo fedha zimekabidhiwa', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_by_staff_name',
            field=models.CharField(blank=True, help_text='Jina la Mtumishi aliyekabidhi Cash', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_by_staff_role',
            field=models.CharField(blank=True, help_text='Cheo cha Mtumishi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_account_no',
            field=models.CharField(blank=True, help_text='Namba ya Simu au Akaunti ya Benki', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(choices=[('CASH', 'Cash (Fedha Taslimu Mkononi)'), ('MOBILE_MONEY', 'Mitandao ya Simu (M-Pesa / Tigo Pesa / Airtel Money)'), ('BANK_TRANSFER', 'Akaunti ya Benki (NMB / CRDB / NBC / Equity)')], default='MOBILE_MONEY', help_text='Njia ya Utoaji wa Fedha', max_length=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_provider',
            field=models.CharField(blank=True, help_text='Mtandao wa Simu au Jina la Benki', max_length=50, null=True),
        ),
    ]
