# Generated by Django 5.2.17 on 2026-08-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_disbursed_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('author_role', models.CharField(default='Loan Officer', max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loans.loan')),
            ],
            options={
                'db_table': 'fkf_ems_loan_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
