# Generated by Django 5.2.17 on 2026-08-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_loancomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='business_photo_url',
            field=models.TextField(blank=True, help_text='Picha ya Anapofanyia Biashara', null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='created_by_officer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='created_by_officer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='field_gps_location',
            field=models.CharField(blank=True, help_text='GPS Coordinates & Location Tag', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='residence_photo_url',
            field=models.TextField(blank=True, help_text='Picha ya Anapokaa', null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='workplace_stand_photo_url',
            field=models.TextField(blank=True, help_text='Picha ya Stendi akiwa Kazini', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by_officer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by_officer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
