# Generated by Django 5.2.17 on 2026-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_borrower_business_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='branch_review_decision',
            field=models.CharField(blank=True, help_text='APPROVED / REJECTED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='branch_review_notes',
            field=models.TextField(blank=True, help_text='Maelezo ya Meneja wa Tawi (Branch Approval Notes)', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='branch_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='branch_reviewed_by',
            field=models.CharField(blank=True, help_text='Jina la Meneja wa Tawi aliyeidhinisha', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_review_decision',
            field=models.CharField(blank=True, help_text='PASSED / FAILED', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_review_notes',
            field=models.TextField(blank=True, help_text='Maelezo ya Tathmini ya Hatari (Risk Review Notes)', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='risk_reviewed_by',
            field=models.CharField(blank=True, help_text='Jina la Afisa wa Tathmini ya Hatari', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING_BRANCH_APPROVAL', 'Inasubiri Idhini ya Meneja wa Tawi'), ('BRANCH_APPROVED', 'Imeidhinishwa na Meneja wa Tawi'), ('BRANCH_REJECTED', 'Imekataliwa na Meneja wa Tawi'), ('PENDING_RISK_REVIEW', 'Inasubiri Tathmini ya Hatari (Risk Review)'), ('RISK_APPROVED', 'Imepita Tathmini ya Hatari – Subiri Super Admin'), ('RISK_FAILED', 'Imeshindwa Tathmini ya Hatari – Imekataliwa'), ('APPROVED', 'Imeidhinishwa Kikamilifu na Makao Makuu'), ('DISBURSED', 'Fedha Zimetolewa kwa Mkopaji'), ('REPAID', 'Imelipwa Kikamilifu'), ('DEFAULTED', 'Imeshindwa Kulipa / Chini ya Urejeshaji')], default='PENDING_BRANCH_APPROVAL', max_length=30),
        ),
    ]
