# Generated by Django 5.2.17 on 2026-08-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loan_branch_review_decision_loan_branch_review_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING_RISK_REVIEW', 'Hatua 1: Ombi Limeingia (Inasubiri Risk Review)'), ('RISK_APPROVED', 'Hatua 2: Imepita Risk Review (Inasubiri Branch Approval)'), ('RISK_FAILED', 'Hatua 2: Imeshindwa Risk Review – Imekataliwa'), ('PENDING_BRANCH_APPROVAL', 'Hatua 3: Inasubiri Idhini ya Meneja wa Tawi'), ('BRANCH_APPROVED', 'Hatua 3: Imeidhinishwa na Tawi (Inasubiri Super Admin Final)'), ('BRANCH_REJECTED', 'Hatua 3: Imekataliwa na Meneja wa Tawi'), ('APPROVED', 'Hatua 4: Imeidhinishwa Kikamilifu na Super Admin Makao Makuu'), ('DISBURSED', 'Fedha Zimetolewa kwa Mkopaji'), ('REPAID', 'Imelipwa Kikamilifu'), ('DEFAULTED', 'Imeshindwa Kulipa / Chini ya Urejeshaji')], default='PENDING_RISK_REVIEW', max_length=30),
        ),
    ]
