# Generated by Django 5.2.17 on 2026-08-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique Branch Identifier, e.g. BR-NBO-01', max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=500000.0, help_text='Maximum allowed loan amount for this branch', max_digits=12)),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, default=14.5, help_text='Base monthly/annual interest rate percentage', max_digits=5)),
                ('penalty_type', models.CharField(choices=[('FLAT', 'Flat Rate (KES)'), ('PERCENTAGE', 'Percentage-Based (%)')], default='PERCENTAGE', max_length=15)),
                ('penalty_value', models.DecimalField(decimal_places=2, default=5.0, help_text='Flat KES value or percentage rate for late penalties', max_digits=10)),
                ('require_collateral', models.BooleanField(default=True)),
                ('collateral_min_ltv_pct', models.DecimalField(decimal_places=2, default=70.0, help_text='Minimum required Loan-to-Value ratio', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'fkf_ems_branches',
                'ordering': ['code'],
            },
        ),
    ]
