# Generated by Django 5.2.17 on 2026-08-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Unique Branch Identifier, e.g. BR-DAR-01', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=5000000.0, help_text='Maximum allowed loan amount for this branch (TSH)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='branch',
            name='penalty_type',
            field=models.CharField(choices=[('FLAT', 'Flat Rate (TSH)'), ('PERCENTAGE', 'Percentage-Based (%)')], default='PERCENTAGE', max_length=15),
        ),
        migrations.AlterField(
            model_name='branch',
            name='penalty_value',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Flat TSH value or percentage rate for late penalties', max_digits=12),
        ),
    ]
