# Generated by Django 5.2.17 on 2026-08-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_code_alter_branch_max_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(default='Ilala', help_text='Wilaya', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.CharField(default='Dar es Salaam', help_text='Mkoa', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='street_or_village',
            field=models.CharField(default='Mtaa wa Swahili', help_text='Mtaa au Kijiji', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='ward',
            field=models.CharField(default='Kariakoo', help_text='Kata', max_length=50),
        ),
    ]
