# Generated by Django 5.2.17 on 2026-08-11 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_region_district_ward_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allocated_capital',
            field=models.DecimalField(decimal_places=2, default=50000000.0, help_text='Total company capital allocated to this branch in TSH', max_digits=16),
        ),
        migrations.CreateModel(
            name='BranchCapitalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(help_text='Username/Name of manager requesting top-up', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount requested in TSH', max_digits=16)),
                ('reason', models.TextField(help_text='Reason for top-up request')),
                ('status', models.CharField(choices=[('PENDING', 'Inasubiri Idhini'), ('APPROVED', 'Imeidhinishwa'), ('REJECTED', 'Imekataliwa')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_requests', to='branches.branch')),
            ],
            options={
                'db_table': 'fkf_ems_branch_capital_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
