# Generated by Django 5.2.17 on 2026-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branch_allocated_capital_branchcapitalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='block_number',
            field=models.CharField(blank=True, default='Block A', help_text='Kitalu / Block No (manual)', max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='house_number',
            field=models.CharField(blank=True, default='Nyumba No 12', help_text='Namba ya Nyumba / House No (manual)', max_length=50),
        ),
    ]
